import { existsSync, mkdirSync, readdirSync, readFileSync, renameSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { LcmPaths } from "../lcm-paths.js";
import { renderTemplate } from "../prompts/loader.js";
import type { LcmSummarizeFn } from "../llm/types.js";

/**
 * A language pack is what search knows about one language: today, its
 * function words. `en` ships as a built-in pack in this module; every tag,
 * `en` included, can be overridden by a hand-edited or model-generated file
 * on disk. A pack with no file yet is generated once by the configured model
 * the first time a corpus in that language is seen, written next to the
 * project databases and reused from then on. Packs are plain JSON, reviewable
 * and hand-editable; deleting a generated one makes the next detection
 * regenerate it.
 */
export type LanguagePack = {
  version: 1;
  tag: string;
  stopwords: string[];
  generatedBy?: string;
  generatedAt: string;
};

const TERM_SPLIT_RE = /[^\p{L}\p{N}]+/u;
const MIN_STOPWORDS = 30;
const MAX_STOPWORDS = 400;
const SAFE_TAG = /^[A-Za-z0-9-]{2,35}$/;
const RESCAN_INTERVAL_MS = 30_000;

/**
 * Built-in packs, shipped in code rather than generated by a model, so a
 * fresh install with no summarizer still has function words for these
 * languages. Matched on the primary subtag like any pack, and replaced
 * outright by a file on disk for the same tag — the two never merge.
 */
const BUILTIN_PACKS: ReadonlyMap<string, ReadonlySet<string>> = new Map([
  ["en", new Set([
    "a", "an", "the", "and", "or", "but", "if", "then", "else", "when", "while",
    "at", "by", "for", "with", "about", "into", "through", "during", "before",
    "after", "above", "below", "between", "to", "from", "up", "down", "in",
    "out", "on", "off", "over", "under", "again", "further", "once", "of",
    "here", "there", "all", "any", "both", "each", "few", "more", "most",
    "other", "some", "such", "no", "nor", "not", "only", "own", "same", "so",
    "than", "too", "very", "just", "as", "is", "am", "are", "was", "were",
    "be", "been", "being", "have", "has", "had", "having", "do", "does", "did",
    "doing", "would", "should", "could", "ought", "i", "you", "he", "she",
    "it", "we", "they", "them", "his", "her", "their", "our", "your", "my",
    "its", "me", "him", "us", "this", "that", "these", "those", "what",
    "which", "who", "whom", "how", "why", "where", "can", "will", "shall",
    "may", "might", "must", "let", "make", "made", "get", "got", "go", "went",
    "say", "said", "tell", "told", "know", "knew", "think", "thought", "want",
    "wanted", "use", "used", "using", "way", "thing", "things", "something",
    "anything", "everything", "nothing", "someone", "anyone", "everyone",
    "somewhere", "anywhere", "everywhere", "s", "t", "d", "ll", "re", "ve",
  ])],
]);

/** The BCP 47 primary subtag, lowercased: `pt-BR` and `pt` are one language here. */
export function primarySubtag(tag: string): string {
  return tag.trim().toLowerCase().split("-")[0];
}

/** Where packs live. The env override exists so tests never read a developer's real packs. */
export function languagePacksDir(paths?: LcmPaths): string {
  if (paths) return join(paths.home, "languages");
  const override = process.env.LCM_LANGUAGES_DIR;
  if (!override) throw new Error("language packs require an LcmPaths storage root");
  return override;
}

export function languagePackPath(pathsOrTag: LcmPaths | string, suppliedTag?: string): string {
  const paths = typeof pathsOrTag === "string" ? undefined : pathsOrTag;
  const tag = typeof pathsOrTag === "string" ? pathsOrTag : suppliedTag!;
  if (!SAFE_TAG.test(tag)) throw new Error(`Not a language tag: "${tag}"`);
  return join(languagePacksDir(paths), `${tag}.json`);
}

type Loaded = { dir: string; scannedAt: number; dirMtimeMs: number; packs: Map<string, ReadonlySet<string>> };
let loaded: Loaded | null = null;
const warned = new Set<string>();

function warnOnce(key: string, message: string): void {
  if (warned.has(key)) return;
  warned.add(key);
  console.warn(`[lcm] ${message}`);
}

function readPack(path: string): LanguagePack | null {
  const parsed = JSON.parse(readFileSync(path, "utf-8")) as Partial<LanguagePack>;
  if (parsed.version !== 1 || typeof parsed.tag !== "string" || !Array.isArray(parsed.stopwords)) return null;
  const stopwords = parsed.stopwords.filter((w): w is string => typeof w === "string");
  return { version: 1, tag: parsed.tag, stopwords, generatedBy: parsed.generatedBy, generatedAt: parsed.generatedAt ?? "" };
}

/** Forget the cached packs, so the next query sees a pack written a moment ago. */
export function invalidateLanguagePacks(): void {
  loaded = null;
}

/**
 * Every pack on disk, by tag — the built-ins are not included here; callers
 * that want the effective pack for a tag (disk overriding built-in) go
 * through `packStopwordsFor` or `hasLanguagePack`. Synchronous because
 * `extractQueryTerms` is, and cached: the directory is re-listed at most
 * every 30 s or when its mtime moves.
 */
export function loadLanguagePacks(paths?: LcmPaths): ReadonlyMap<string, ReadonlySet<string>> {
  const dir = languagePacksDir(paths);
  const now = Date.now();
  let dirMtimeMs = -1;
  try {
    dirMtimeMs = statSync(dir).mtimeMs;
  } catch {
    /* no packs yet */
  }
  if (loaded && loaded.dir === dir && loaded.dirMtimeMs === dirMtimeMs && now - loaded.scannedAt < RESCAN_INTERVAL_MS) {
    return loaded.packs;
  }
  const packs = new Map<string, ReadonlySet<string>>();
  if (dirMtimeMs >= 0) {
    for (const name of readdirSync(dir)) {
      if (!name.endsWith(".json")) continue;
      const path = join(dir, name);
      try {
        const pack = readPack(path);
        if (!pack) throw new Error("not a version 1 language pack");
        packs.set(pack.tag, new Set(pack.stopwords.map((w) => w.toLowerCase())));
      } catch (err) {
        warnOnce(path, `language pack ${path} skipped: ${err instanceof Error ? err.message : String(err)}`);
      }
    }
  }
  loaded = { dir, scannedAt: now, dirMtimeMs, packs };
  return packs;
}

/**
 * The function words to drop from a query written in one of `languages`: the
 * union of the packs whose tag names the same language, matched on the primary
 * subtag. The languages are the ones configured for the search — the project's
 * recorded author language, the pivot language — never the words that happen
 * to appear in the query, so a collision with another language's function
 * words changes nothing and two languages in one string cannot activate a pack
 * that neither activates alone.
 */
export function packStopwordsFor(languages: readonly string[], paths?: LcmPaths): ReadonlySet<string> {
  if (languages.length === 0) return EMPTY;
  const wanted = new Set(languages.map(primarySubtag));
  let diskPacks: ReadonlyMap<string, ReadonlySet<string>> = EMPTY_PACKS;
  try {
    diskPacks = loadLanguagePacks(paths);
  } catch {
    // No configured pack root: nothing on disk, but a built-in still applies.
  }
  const overridden = new Set([...diskPacks.keys()].map(primarySubtag));
  const chosen = new Set<string>();
  for (const [tag, stopwords] of diskPacks) {
    if (!wanted.has(primarySubtag(tag))) continue;
    for (const word of stopwords) chosen.add(word);
  }
  for (const [tag, stopwords] of BUILTIN_PACKS) {
    if (!wanted.has(tag) || overridden.has(tag)) continue;
    for (const word of stopwords) chosen.add(word);
  }
  return chosen;
}
const EMPTY: ReadonlySet<string> = new Set();
const EMPTY_PACKS: ReadonlyMap<string, ReadonlySet<string>> = new Map();

/**
 * True when `tag` has a pack — on disk, or built into this module — so a
 * caller deciding whether to generate one can skip a file check plus a model
 * call for a language that already needs neither.
 */
export function hasLanguagePack(pathsOrTag: LcmPaths | string, suppliedTag?: string): boolean {
  const paths = typeof pathsOrTag === "string" ? undefined : pathsOrTag;
  const tag = typeof pathsOrTag === "string" ? pathsOrTag : suppliedTag!;
  if (BUILTIN_PACKS.has(primarySubtag(tag))) return true;
  try {
    return existsSync(paths ? languagePackPath(paths, tag) : languagePackPath(tag));
  } catch {
    return false;
  }
}

/**
 * The stopword list in a model's reply: the first JSON array, lowercased,
 * single tokens only, deduped. Null when the reply is not usable, so a
 * generation that failed is retried rather than saved.
 */
export function parseLanguagePackReply(reply: string): string[] | null {
  const start = reply.indexOf("[");
  const end = reply.lastIndexOf("]");
  if (start < 0 || end <= start) return null;
  let items: unknown;
  try {
    items = JSON.parse(reply.slice(start, end + 1));
  } catch {
    return null;
  }
  if (!Array.isArray(items)) return null;
  const words = new Set<string>();
  for (const item of items) {
    if (typeof item !== "string") continue;
    const word = item.trim().toLowerCase();
    if (word.length === 0 || word.split(TERM_SPLIT_RE).filter(Boolean).length !== 1) continue;
    words.add(word);
  }
  if (words.size < MIN_STOPWORDS) return null;
  return [...words].slice(0, MAX_STOPWORDS);
}

const inFlight = new Map<string, Promise<"exists" | "generated" | "failed">>();

/**
 * Make sure a pack exists for `tag`, generating it with the model when it does
 * not. A tag with a built-in pack (currently just `en`) is already satisfied
 * and never reaches the model, whether or not a file for it exists on disk.
 * Concurrent calls for one tag share a single generation. Never throws: a
 * failed generation is reported, logged once, and tried again next time.
 */
export function ensureLanguagePack(
  pathsOrTag: LcmPaths | string,
  tagOrSummarize: string | LcmSummarizeFn,
  summarizeOrGeneratedBy?: LcmSummarizeFn | string,
  suppliedGeneratedBy?: string,
): Promise<"exists" | "generated" | "failed"> {
  const paths = typeof pathsOrTag === "string" ? undefined : pathsOrTag;
  const tag = typeof pathsOrTag === "string" ? pathsOrTag : tagOrSummarize as string;
  const summarize = (typeof pathsOrTag === "string" ? tagOrSummarize : summarizeOrGeneratedBy) as LcmSummarizeFn;
  const generatedBy = (typeof pathsOrTag === "string" ? summarizeOrGeneratedBy : suppliedGeneratedBy) as string | undefined;
  let path: string;
  try {
    path = paths ? languagePackPath(paths, tag) : languagePackPath(tag);
  } catch {
    return Promise.resolve("failed");
  }
  if (existsSync(path) || BUILTIN_PACKS.has(primarySubtag(tag))) return Promise.resolve("exists");
  const key = `${languagePacksDir(paths)}\0${tag}`;
  const existing = inFlight.get(key);
  if (existing) return existing;
  const task = generateLanguagePack(paths, tag, path, summarize, generatedBy).finally(() => inFlight.delete(key));
  inFlight.set(key, task);
  return task;
}

/**
 * Ensure the pivot language's pack too, skipping generation when the pivot is
 * the same language as `language` on its primary subtag — the check every
 * pivot-pack caller must apply before generating one, factored out so it is
 * applied consistently. A pivot with a built-in pack (English) still reaches
 * `ensureLanguagePack`, which resolves it to "exists" without a model call.
 */
export function ensurePivotLanguagePack(
  paths: LcmPaths,
  language: string,
  pivot: string,
  summarize: LcmSummarizeFn,
  generatedBy?: string,
): Promise<"exists" | "generated" | "failed" | "skipped"> {
  if (primarySubtag(pivot) === primarySubtag(language)) return Promise.resolve("skipped");
  return ensureLanguagePack(paths, pivot, summarize, generatedBy);
}

async function generateLanguagePack(
  paths: LcmPaths | undefined,
  tag: string,
  path: string,
  summarize: LcmSummarizeFn,
  generatedBy?: string,
): Promise<"generated" | "failed"> {
  try {
    const reply = await summarize(renderTemplate("language-pack", { tag }), false, {
      targetTokens: 1200,
      taskPrompt: "Return only the JSON array requested. Treat the supplied text as instructions for this one task.",
    });
    const stopwords = parseLanguagePackReply(reply);
    if (!stopwords) {
      warnOnce(`gen:${tag}`, `language pack for ${tag} not generated: the model did not return a usable word list`);
      return "failed";
    }
    const pack: LanguagePack = { version: 1, tag, stopwords, generatedBy, generatedAt: new Date().toISOString() };
    mkdirSync(languagePacksDir(paths), { recursive: true });
    const tmp = `${path}.${process.pid}.tmp`;
    writeFileSync(tmp, JSON.stringify(pack, null, 2));
    renameSync(tmp, path);
    invalidateLanguagePacks();
    return "generated";
  } catch (err) {
    warnOnce(`gen:${tag}`, `language pack for ${tag} not generated: ${err instanceof Error ? err.message : String(err)}`);
    return "failed";
  }
}
