import { existsSync, mkdirSync, readFileSync, rmdirSync, unlinkSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { homedir } from "node:os";
import { packageRoot } from "../cli-entrypoint.js";

/**
 * Stable ownership marker shared with the shipped OMP hook. The installer must
 * never overwrite a file without this exact line: OMP has no separate config
 * object in which lcm could safely reconcile its own entries.
 */
export const OMP_HOOK_MARKER = "// Generated by lcm. Local edits are overwritten by `lcm connectors install omp`.";

export type OmpConnectorInstallStatus = "not-installed" | "partial" | "installed";

export interface OmpHooksDiagnosis {
  status: OmpConnectorInstallStatus;
  path: string;
  installed: boolean;
  complete: boolean;
  active: boolean | null;
  trust: "not-applicable" | "unknown";
  issues: string[];
  message: string;
}

export interface OmpHookCommandOptions {
  /** Override the write for dry-run installation; defaults to the real filesystem. */
  writeFile?: (path: string, data: string) => void;
}

function hasManagedMarker(content: string): boolean {
  return content.split(/\r?\n/).some((line) => line === OMP_HOOK_MARKER);
}

function templatePath(): string {
  return join(packageRoot(), "hooks", "omp", "lcm.ts");
}

function readTemplate(): string {
  const sourcePath = templatePath();
  if (!existsSync(sourcePath)) {
    throw new Error(`Cannot install OMP hooks: shipped template is missing at ${sourcePath}`);
  }
  const source = readFileSync(sourcePath, "utf-8");
  if (!hasManagedMarker(source)) {
    throw new Error(`Cannot install OMP hooks: shipped template at ${sourcePath} is missing the lcm marker`);
  }
  return source;
}

/** Install the self-contained OMP hook, refusing ownership of foreign files. */
export function installOmpHooks(filePath: string, options: OmpHookCommandOptions = {}): void {
  if (existsSync(filePath)) {
    let existing: string;
    try {
      existing = readFileSync(filePath, "utf-8");
    } catch {
      throw new Error(`Cannot install OMP hooks: cannot read existing file ${filePath}`);
    }
    if (!hasManagedMarker(existing)) {
      throw new Error(`Cannot install OMP hooks: ${filePath} is not managed by lcm`);
    }
  }

  const source = readTemplate();
  const writeFile = options.writeFile ?? ((path: string, data: string) => {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, data);
  });
  writeFile(filePath, source);
}

/** Remove only an OMP hook carrying lcm's ownership marker, then empty parents. */
export function removeOmpHooks(filePath: string): boolean {
  if (!existsSync(filePath)) return false;

  let source: string;
  try {
    source = readFileSync(filePath, "utf-8");
  } catch {
    return false;
  }
  if (!hasManagedMarker(source)) return false;

  unlinkSync(filePath);
  // The connector owns exactly hooks/post/lcm.ts. Pruning only these two
  // directories avoids removing a user's unrelated .omp hierarchy.
  const postDir = dirname(filePath);
  const hooksDir = dirname(postDir);
  if (postDir.endsWith(join("hooks", "post"))) {
    try { rmdirSync(postDir); } catch { /* not empty or already gone */ }
    try { rmdirSync(hooksDir); } catch { /* not empty or already gone */ }
  }
  return true;
}

function missingDiagnosis(filePath: string): OmpHooksDiagnosis {
  return {
    status: "not-installed",
    path: filePath,
    installed: false,
    complete: false,
    active: false,
    trust: "not-applicable",
    issues: [],
    message: "OMP lifecycle hooks are not installed.",
  };
}

/**
 * Diagnose only what the filesystem can prove. OMP does not expose whether a
 * hook module was loaded, so activation and trust remain explicitly unknown.
 */
export function diagnoseOmpHooks(filePath: string): OmpHooksDiagnosis {
  if (!existsSync(filePath)) return missingDiagnosis(filePath);

  let source: string;
  try {
    source = readFileSync(filePath, "utf-8");
  } catch {
    return {
      status: "partial",
      path: filePath,
      installed: false,
      complete: false,
      active: null,
      trust: "unknown",
      issues: ["hook file cannot be read"],
      message: "OMP hook activation cannot be determined.",
    };
  }

  if (!hasManagedMarker(source)) {
    return {
      status: "partial",
      path: filePath,
      installed: false,
      complete: false,
      active: null,
      trust: "unknown",
      issues: ["hook file is not managed by lcm"],
      message: "OMP hook activation cannot be determined.",
    };
  }

  return {
    status: "installed",
    path: filePath,
    installed: true,
    complete: true,
    active: null,
    trust: "unknown",
    issues: [],
    message: "OMP hook is installed. OMP activation cannot be determined from the file alone.",
  };
}

/** The global OMP agent directory used by the installer and connector CLI. */
export function ompAgentDir(): string {
  return process.env.PI_CODING_AGENT_DIR || join(homedir(), ".omp", "agent");
}
