/**
 * Named summarizer endpoints: `llm.providers`, `llm.provider` naming one of them,
 * and `llm.fallback` listing the rest in order. Validated once at config load, so a
 * bad endpoint fails there rather than as an opaque HTTP error during a compaction.
 *
 * The one exception is an environment variable an endpoint references and the
 * environment lacks: the daemon runs in whatever environment started it, which need
 * not hold every key. That endpoint is marked unavailable and left out of the chain,
 * and the rest of the config loads.
 */

export type HttpEndpointType = "openai" | "anthropic";
export type ProcessEndpointType = "claude-process" | "codex-process" | "copilot-process";

export type HttpEndpoint = {
  type: HttpEndpointType;
  model: string;
  baseURL?: string;
  apiKey?: string;
  /** Extra top-level request fields, merged under the fields lcm generates. */
  body?: Record<string, unknown>;
  /** Variables `apiKey` or `baseURL` reference that were unset at load: the endpoint cannot run. */
  missingEnv?: string[];
};
export type ProcessEndpoint = { type: ProcessEndpointType; model?: string };
export type EndpointConfig = HttpEndpoint | ProcessEndpoint;

const HTTP_TYPES: ReadonlySet<string> = new Set<HttpEndpointType>(["openai", "anthropic"]);
const PROCESS_TYPES: ReadonlySet<string> = new Set<ProcessEndpointType>(["claude-process", "codex-process", "copilot-process"]);
const SELECTORS = new Set(["session", "auto", "disabled"]);
const PROTOTYPE_KEYS = new Set(["__proto__", "constructor", "prototype"]);
/** Names that already mean something as a provider value, so an endpoint cannot take them. */
const RESERVED_NAMES = new Set([...SELECTORS, ...HTTP_TYPES, ...PROCESS_TYPES, "claude-cli", ...PROTOTYPE_KEYS]);
const ENDPOINT_NAME = /^[A-Za-z0-9][A-Za-z0-9_.-]*$/;

const HTTP_FIELDS = new Set(["type", "model", "baseURL", "apiKey", "body"]);
const PROCESS_FIELDS = new Set(["type", "model"]);

/**
 * Request fields lcm generates or owns. A body may add fields next to them, never
 * replace them: the prompt, the model, the output budget and the response shape
 * are what make an answer a summary lcm can judge.
 */
const OWNED_BODY_FIELDS = new Set([
  "model", "messages", "system", "prompt", "input",
  "stream", "stream_options",
  "max_tokens", "max_completion_tokens", "max_output_tokens", "max_new_tokens",
  "n", "tools", "tool_choice", "functions", "function_call", "parallel_tool_calls",
  "response_format", "text",
  // OpenRouter cost accounting, which the openai adapter requests itself.
  "usage",
]);

type LlmSection = {
  provider: string;
  fallbackProvider?: string;
  model?: string;
  apiKey?: string;
  baseURL?: string;
  reasoning?: unknown;
  providers?: unknown;
  fallback?: unknown;
};

function fail(message: string): never {
  throw new Error(`[lcm] ${message}`);
}

function isPlainObject(value: unknown): value is Record<string, unknown> {
  if (typeof value !== "object" || value === null || Array.isArray(value)) return false;
  const proto = Object.getPrototypeOf(value);
  return proto === Object.prototype || proto === null;
}

function describeType(value: unknown): string {
  return Array.isArray(value) ? "array" : value === null ? "null" : typeof value;
}


/** null, a boolean, a string or a finite number: the scalars JSON can hold. */
function isJsonScalar(value: unknown): boolean {
  return value === null || typeof value === "boolean" || typeof value === "string"
    || (typeof value === "number" && Number.isFinite(value));
}

/**
 * Accepts only what JSON.parse can produce, with no prototype key at any depth. A
 * config file cannot hold anything else, but programmatic overrides can.
 */
function assertPlainJson(value: unknown, where: string): void {
  if (isJsonScalar(value)) return;
  if (Array.isArray(value)) {
    value.forEach((item, i) => assertPlainJson(item, `${where}[${i}]`));
    return;
  }
  if (!isPlainObject(value)) fail(`${where} must be a JSON value (got ${describeType(value)})`);
  for (const key of Object.keys(value)) {
    if (PROTOTYPE_KEYS.has(key)) fail(`${where} holds the prototype key "${key}"`);
    assertPlainJson(value[key], `${where}.${key}`);
  }
}

/** A body is a plain JSON object whose top-level fields lcm does not own. */
export function validateRequestBody(body: unknown, where: string): Record<string, unknown> {
  if (!isPlainObject(body)) fail(`${where} must be a JSON object (got ${describeType(body)})`);
  for (const key of Object.keys(body)) {
    if (OWNED_BODY_FIELDS.has(key)) fail(`${where}.${key} is generated by lcm and cannot be set in a body`);
  }
  assertPlainJson(body, where);
  return body;
}

/** `${NAME}` interpolation; an unset variable is recorded in `missing`, never sent as an empty value. */
/** The environment `${NAME}` reads from, and the unset names found so far. */
type Expansion = { env: Record<string, string | undefined>; missing: string[] };

function expandEnv(raw: unknown, where: string, { env, missing }: Expansion): string {
  if (typeof raw !== "string") fail(`${where} must be a string`);
  return raw.replace(/\$\{(\w+)\}/g, (_: string, name: string) => {
    const value = env[name];
    if (!value && !missing.includes(name)) missing.push(name);
    return value ?? "";
  });
}

/** Without its own key, an `anthropic` endpoint uses ANTHROPIC_API_KEY, as the flat form does. */
function defaultApiKey(type: HttpEndpointType, { env, missing }: Expansion): string | undefined {
  if (type !== "anthropic") return undefined;
  if (!env.ANTHROPIC_API_KEY) missing.push("ANTHROPIC_API_KEY");
  return env.ANTHROPIC_API_KEY || undefined;
}

function isHttpUrl(value: unknown): value is string {
  if (typeof value !== "string") return false;
  try {
    return /^https?:$/.test(new URL(value).protocol);
  } catch {
    return false; // not a URL at all
  }
}

function assertFields(entry: Record<string, unknown>, allowed: ReadonlySet<string>, reject: (key: string) => string): void {
  const unknown = Object.keys(entry).find((key) => !allowed.has(key));
  if (unknown) fail(reject(unknown));
}

function normalizeProcessEndpoint(where: string, type: ProcessEndpointType, entry: Record<string, unknown>): ProcessEndpoint {
  assertFields(entry, PROCESS_FIELDS, (key) => `${where}.${key} does not apply to ${type}, which runs its own CLI and uses its login`);
  if (entry.model !== undefined && typeof entry.model !== "string") fail(`${where}.model must be a string`);
  return { type, ...(entry.model ? { model: entry.model as string } : {}) };
}

function normalizeHttpEndpoint(where: string, entry: Record<string, unknown>, env: Record<string, string | undefined>): HttpEndpoint {
  const type = entry.type as HttpEndpointType;
  assertFields(entry, HTTP_FIELDS, (key) => `${where}.${key} is not an endpoint field; a request field goes in ${where}.body`);
  if (typeof entry.model !== "string" || !entry.model.trim()) fail(`${where}.model must name the model`);
  const missing: string[] = [];
  const expansion: Expansion = { env, missing };
  const baseURL = entry.baseURL === undefined ? undefined : expandEnv(entry.baseURL, `${where}.baseURL`, expansion);
  // A URL built from an unset variable is not checked: the endpoint will not run anyway.
  if (baseURL !== undefined && missing.length === 0 && !isHttpUrl(baseURL)) fail(`${where}.baseURL must be an http(s) URL`);
  const apiKey = entry.apiKey !== undefined
    ? expandEnv(entry.apiKey, `${where}.apiKey`, expansion)
    : defaultApiKey(type, expansion);
  return {
    type, model: entry.model,
    ...(baseURL !== undefined ? { baseURL } : {}),
    ...(apiKey !== undefined ? { apiKey } : {}),
    ...(entry.body !== undefined ? { body: validateRequestBody(entry.body, `${where}.body`) } : {}),
    ...(missing.length > 0 ? { missingEnv: missing } : {}),
  };
}

function normalizeEndpoint(name: string, entry: unknown, env: Record<string, string | undefined>): EndpointConfig {
  const where = `llm.providers.${name}`;
  if (!ENDPOINT_NAME.test(name)) fail(`llm.providers: "${name}" is not a valid endpoint name (letters, digits, "_", "-", ".")`);
  if (RESERVED_NAMES.has(name)) fail(`llm.providers: "${name}" is reserved; give the endpoint another name`);
  if (!isPlainObject(entry)) fail(`${where} must be a JSON object`);
  const type = String(entry.type);
  if (PROCESS_TYPES.has(type)) return normalizeProcessEndpoint(where, type as ProcessEndpointType, entry);
  if (HTTP_TYPES.has(type)) return normalizeHttpEndpoint(where, entry, env);
  fail(`${where}.type must be one of ${[...HTTP_TYPES, ...PROCESS_TYPES].join(", ")}`);
}

function resolveSelection(value: string, providers: Record<string, EndpointConfig>, source: string): string {
  if (SELECTORS.has(value) || Object.hasOwn(providers, value)) return value;
  const valid = [...SELECTORS, ...Object.keys(providers)].join(", ");
  if (!HTTP_TYPES.has(value) && !PROCESS_TYPES.has(value)) fail(`Invalid ${source}="${value}". Valid values: ${valid}`);
  const matches = Object.keys(providers).filter((name) => providers[name].type === value);
  if (matches.length !== 1) {
    fail(`${source}="${value}" is a provider type, and ${matches.length} endpoints in llm.providers have it; ` +
      `name one endpoint instead. Valid values: ${valid}`);
  }
  return matches[0];
}

/** The flat connection fields describe one endpoint; with several, each endpoint holds its own. */
function rejectFlatFields(llm: LlmSection, supplied: ReadonlySet<string>): void {
  for (const field of ["model", "apiKey", "baseURL"] as const) {
    // The defaults fill these with "", so an empty value counts only when the config supplied it.
    if (llm[field] || supplied.has(field)) fail(`llm.${field} cannot be combined with llm.providers: set it on an endpoint`);
  }
  if (llm.reasoning !== undefined) {
    fail("llm.reasoning cannot be combined with llm.providers: set llm.providers.<name>.body.reasoning");
  }
  if (llm.fallbackProvider !== undefined) {
    fail("llm.fallbackProvider cannot be combined with llm.providers: list endpoint names in llm.fallback");
  }
}

function normalizeFallback(fallback: unknown, providers: Record<string, EndpointConfig>): string[] {
  if (!Array.isArray(fallback) || !fallback.every((name) => typeof name === "string")) {
    fail("llm.fallback must be an array of endpoint names");
  }
  const missing = fallback.find((name) => !Object.hasOwn(providers, name));
  if (missing !== undefined) fail(`llm.fallback names "${missing}", which is not an endpoint in llm.providers`);
  return fallback;
}

/**
 * Validates `llm` when it declares `llm.providers`, in place: keys are expanded, the
 * primary selection resolved (`LCM_SUMMARY_PROVIDER` first) and `fallback` defaulted.
 * Without `llm.providers`, only rejects `llm.fallback`, which needs named endpoints.
 */
export function normalizeNamedEndpoints(
  llm: LlmSection, env: Record<string, string | undefined>, supplied: ReadonlySet<string> = new Set(),
): void {
  if (llm.providers === undefined) {
    if (llm.fallback !== undefined) fail("llm.fallback needs llm.providers; with the flat form, set llm.fallbackProvider");
    return;
  }
  if (!isPlainObject(llm.providers)) fail("llm.providers must be a JSON object mapping endpoint names to endpoints");
  rejectFlatFields(llm, supplied);
  const providers: Record<string, EndpointConfig> = {};
  for (const [name, entry] of Object.entries(llm.providers)) providers[name] = normalizeEndpoint(name, entry, env);
  const fallback = normalizeFallback(llm.fallback ?? [], providers);

  const override = env.LCM_SUMMARY_PROVIDER;
  const provider = override
    ? resolveSelection(override, providers, "LCM_SUMMARY_PROVIDER")
    : resolveSelection(llm.provider, providers, "llm.provider");
  // The environment may promote a fallback endpoint to primary; the chain still runs it once.
  const links = override ? fallback : [provider, ...fallback];
  const repeated = links.find((name, i) => links.indexOf(name) !== i);
  if (repeated) fail(`llm.provider and llm.fallback list "${repeated}" more than once; each endpoint runs once`);

  llm.providers = providers;
  llm.fallback = fallback;
  llm.provider = provider;
}

export type UnavailableEndpoint = { name: string; missingEnv: string[] };

type NamedLlm = { provider: string; providers?: Record<string, EndpointConfig>; fallback?: string[] };

/** The declared endpoints that cannot run, with the variables each one lacks, in declaration order. */
export function unavailableEndpoints(llm: Pick<NamedLlm, "providers">): UnavailableEndpoint[] {
  return Object.entries(llm.providers ?? {}).flatMap(([name, endpoint]) =>
    "missingEnv" in endpoint && endpoint.missingEnv ? [{ name, missingEnv: endpoint.missingEnv }] : []);
}

/**
 * What `/health` and `lcm doctor` report: the chain as configured, which of its
 * endpoints are left out, and whether that leaves nothing to summarize with.
 * The flat form has no named chain and reports an empty one.
 */
export function summarizerAvailability(llm: NamedLlm): { chain: string[]; unavailable: UnavailableEndpoint[]; allUnavailable: boolean } {
  if (!llm.providers) return { chain: [], unavailable: [], allUnavailable: false };
  const chain = [...new Set([llm.provider, ...(llm.fallback ?? [])])];
  const unavailable = unavailableEndpoints(llm).filter(({ name }) => chain.includes(name));
  return { chain, unavailable, allUnavailable: chain.length === unavailable.length };
}
