// Generated by lcm. Local edits are overwritten by `lcm connectors install omp`.
// lcm's Oh My Pi hook adapter.
//
// The local interfaces mirror OMP v18.2.6's `extensibility/hooks` types. The
// adapter is loaded directly by Bun, so it deliberately depends only on Node
// builtins and keeps the daemon protocol here instead of importing this package.
import { readFileSync } from "node:fs";
import { request as httpRequest } from "node:http";
import { Buffer } from "node:buffer";
import { join } from "node:path";

const DEFAULT_PORT = 3737;
const DEFAULT_TIMEOUT_MS = 1_500;
const SHUTDOWN_TIMEOUT_MS = 250;
const TOOL_CONTENT_CAP = 2_000;

export interface HookLogger {
  error?: (message: string) => void;
  warn?: (message: string) => void;
  info?: (message: string) => void;
}

export interface HookContext {
  cwd?: string;
  hasUI?: boolean;
  model?: unknown;
  sessionManager?: {
    getSessionId?: () => string | undefined;
    getSessionFile?: () => string | undefined;
    getCwd?: () => string | undefined;
  };
}

export type HookHandler = (event: unknown, ctx: HookContext) => Promise<unknown> | unknown;

/** The small part of OMP's hook API this module needs. */
export interface HookApi {
  on: (event: string, handler: HookHandler) => void;
  sendMessage?: (message: unknown, options?: unknown) => unknown;
  logger?: HookLogger | ((message: string) => void);
}

export interface ResolvedDaemon {
  home: string;
  port: number;
  token?: string;
}

export interface SessionIdentity {
  sessionId: string;
  cwd: string;
  transcriptPath?: string;
}

export interface PostOptions {
  timeoutMs?: number;
  /** Capture calls use this so the hook never waits for the daemon response. */
  fireAndForget?: boolean;
}

export interface TransportRequest {
  path: string;
  body: Record<string, unknown>;
  port: number;
  token?: string;
  timeoutMs: number;
  fireAndForget: boolean;
}

export type Transport = (request: TransportRequest) => Promise<unknown | undefined> | unknown;

export interface SessionStartEvent {
  type?: string;
}

export interface BeforeAgentStartEvent {
  type?: string;
  prompt: string;
  images?: unknown;
  systemPrompt?: string;
}

export interface AgentEndEvent {
  type?: string;
  messages?: unknown;
  willContinue?: boolean;
}

export interface SessionStopEvent {
  type?: string;
  session_id?: string;
  session_file?: string;
  messages?: unknown;
  turn_id?: string;
  last_assistant_message?: string;
  stop_hook_active?: boolean;
  signal?: string;
}

export interface ToolResultEvent {
  toolName: string;
  toolCallId?: string;
  input?: unknown;
  content?: unknown;
  details?: unknown;
  isError?: boolean;
}

export interface SessionBeforeCompactEvent {
  type?: string;
  preparation?: unknown;
  branchEntries?: unknown;
  customInstructions?: string;
  signal?: string;
}

export interface SessionShutdownEvent {
  type?: string;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function safeString(value: unknown): string | undefined {
  return typeof value === "string" && value.trim() ? value : undefined;
}

/** Resolve the daemon address without letting malformed local state break the host. */
export function resolveDaemon(): ResolvedDaemon {
  const configuredHome = typeof process.env.LCM_HOME === "string" ? process.env.LCM_HOME.trim() : "";
  const homeRoot = configuredHome || (typeof process.env.HOME === "string" ? process.env.HOME.trim() : "");
  const home = homeRoot ? (configuredHome || join(homeRoot, ".lossless-claude")) : ".lossless-claude";

  let port = DEFAULT_PORT;
  try {
    const config = JSON.parse(readFileSync(join(home, "config.json"), "utf8")) as unknown;
    const configuredPort = isRecord(config) && isRecord(config.daemon) ? config.daemon.port : undefined;
    if (typeof configuredPort === "number" && Number.isFinite(configuredPort)) port = configuredPort;
  } catch {
    // A missing or partially-written config is equivalent to the default config.
  }

  let token: string | undefined;
  try {
    const value = readFileSync(join(home, "daemon.token"), "utf8").trim();
    if (value) token = value;
  } catch {
    // Authentication is optional for older or development daemons.
  }
  return token ? { home, port, token } : { home, port };
}

function clearTimer(timer: ReturnType<typeof setTimeout>): void {
  clearTimeout(timer);
}

/** Node transport used in production; sockets and timers are unreferenced for capture calls. */
const nodeTransport: Transport = (request) => new Promise<unknown | undefined>((resolve) => {
  let json: string;
  try {
    json = JSON.stringify(request.body);
  } catch {
    resolve(undefined);
    return;
  }

  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), request.timeoutMs);
  timeout.unref?.();
  let settled = false;
  const finish = (value: unknown | undefined): void => {
    if (settled) return;
    settled = true;
    clearTimer(timeout);
    resolve(value);
  };

  let req: ReturnType<typeof httpRequest>;
  try {
    req = httpRequest({
      hostname: "127.0.0.1",
      port: request.port,
      path: request.path,
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Content-Length": Buffer.byteLength(json),
        ...(request.token ? { Authorization: `Bearer ${request.token}` } : {}),
      },
    }, (res) => {
      if (request.fireAndForget) {
        res.resume();
        return;
      }
      const chunks: Buffer[] = [];
      res.on("data", (chunk: Buffer | string) => chunks.push(Buffer.from(chunk)));
      res.on("end", () => {
        if ((res.statusCode ?? 0) < 200 || (res.statusCode ?? 0) >= 300) {
          finish(undefined);
          return;
        }
        const text = Buffer.concat(chunks).toString("utf8").trim();
        if (!text) {
          finish(undefined);
          return;
        }
        try {
          finish(JSON.parse(text) as unknown);
        } catch {
          finish(undefined);
        }
      });
    });
  } catch {
    finish(undefined);
    return;
  }

  const onAbort = (): void => {
    req.destroy(new Error("daemon request timed out"));
  };
  controller.signal.addEventListener("abort", onAbort, { once: true });
  req.on("error", () => finish(undefined));
  req.setTimeout(request.timeoutMs, () => controller.abort());
  if (request.fireAndForget) {
    req.on("socket", (socket) => {
      req.on("finish", () => socket.unref());
    });
  }
  try {
    req.write(json);
    req.end();
  } catch {
    finish(undefined);
    return;
  }

  // The caller must not wait for capture requests. The socket is unreferenced
  // after the body flushes, while errors remain intentionally best-effort.
  if (request.fireAndForget) {
    settled = true;
    clearTimer(timeout);
    resolve(undefined);
  }
});

let activeTransport: Transport = nodeTransport;

/** Replace the wire transport in focused tests; passing undefined restores Node HTTP. */
export function __setTransportForTests(transport?: Transport): void {
  activeTransport = transport ?? nodeTransport;
}

/** POST JSON to the local daemon, failing closed when it is unavailable. */
export async function post(
  path: string,
  body: Record<string, unknown>,
  options: PostOptions = {},
): Promise<unknown | undefined> {
  const daemon = resolveDaemon();
  const request: TransportRequest = {
    path: path.startsWith("/") ? path : `/${path}`,
    body,
    port: daemon.port,
    token: daemon.token,
    timeoutMs: options.timeoutMs ?? DEFAULT_TIMEOUT_MS,
    fireAndForget: options.fireAndForget === true,
  };

  if (request.fireAndForget) {
    try {
      Promise.resolve(activeTransport(request)).catch(() => undefined);
    } catch {
      // Capture is deliberately best-effort.
    }
    return undefined;
  }
  try {
    return await activeTransport(request);
  } catch {
    return undefined;
  }
}

/** Read the identity that is valid for every daemon call. */
export function sessionIdentity(ctx: HookContext | undefined): SessionIdentity | undefined {
  try {
    const sessionId = ctx?.sessionManager?.getSessionId?.();
    const cwd = ctx?.cwd;
    if (typeof sessionId !== "string" || !sessionId.trim() || typeof cwd !== "string" || !cwd.trim()) return undefined;
    const transcriptPath = safeString(ctx?.sessionManager?.getSessionFile?.());
    return transcriptPath ? { sessionId, cwd, transcriptPath } : { sessionId, cwd };
  } catch {
    return undefined;
  }
}

function sessionStopIdentity(ctx: HookContext | undefined, event: SessionStopEvent): SessionIdentity | undefined {
  const current = sessionIdentity(ctx);
  const sessionId = current?.sessionId ?? safeString(event.session_id);
  const cwd = current?.cwd;
  if (!sessionId || !cwd) return undefined;
  const transcriptPath = current?.transcriptPath ?? safeString(event.session_file);
  return transcriptPath ? { sessionId, cwd, transcriptPath } : { sessionId, cwd };
}

function identityBody(identity: SessionIdentity): Record<string, unknown> {
  return {
    session_id: identity.sessionId,
    cwd: identity.cwd,
    client: "omp",
  };
}

function ingestBody(identity: SessionIdentity): Record<string, unknown> {
  return {
    ...identityBody(identity),
    ...(identity.transcriptPath ? { transcript_path: identity.transcriptPath } : {}),
    source: "live",
  };
}

function logError(pi: HookApi, label: string, error: unknown): void {
  try {
    const message = `[lcm] ${label}: ${error instanceof Error ? error.message : String(error)}`;
    if (typeof pi.logger === "function") pi.logger(message);
    else if (pi.logger?.error) pi.logger.error(message);
    else if (pi.logger?.warn) pi.logger.warn(message);
    else pi.logger?.info?.(message);
  } catch {
    // Logging must not become a hook failure.
  }
}

function modelName(ctx: HookContext): string | undefined {
  const model = ctx.model;
  if (typeof model === "string" && model.trim()) return model;
  if (!isRecord(model)) return undefined;
  return safeString(model.id) ?? safeString(model.name);
}

function boundedToolContent(value: unknown): string | undefined {
  if (value === undefined) return undefined;
  let text: string;
  if (typeof value === "string") text = value;
  else {
    const texts = (Array.isArray(value) ? value : [])
      .filter(isRecord)
      .map((block) => block.text)
      .filter((part): part is string => typeof part === "string");
    if (texts.length > 0) {
      // OMP tool results are content blocks; a decision's answer must read as
      // text, not as its JSON envelope.
      text = texts.join("\n");
    } else {
      try {
        text = JSON.stringify(value) ?? String(value);
      } catch {
        text = String(value);
      }
    }
  }
  return text.length > TOOL_CONTENT_CAP ? `${text.slice(0, TOOL_CONTENT_CAP)}...` : text;
}

function memoryMessage(content: string): { message: Record<string, unknown> } {
  return {
    message: {
      customType: "lcm-memory",
      content,
      display: true,
      attribution: "agent",
    },
  };
}

/**
 * OMP's built-in tool ids are lowercase (`read`, `bash`, `ast_edit`, …) and the
 * daemon's passive-learning extractor is written against the capitalized
 * harness names, so an unmapped call records nothing at all. This mirrors what
 * the Codex adapter does for its own local names: translate the tool and, where
 * the extractor reads a differently named field, translate that too.
 */
export function normalizeOmpTool(
  toolName: string,
  toolInput: Record<string, unknown>,
  toolContent: string | undefined,
): { tool_name: string; tool_input: Record<string, unknown>; tool_response?: string } {
  const rename: Record<string, string> = {
    read: "Read",
    write: "Write",
    edit: "Edit",
    glob: "Glob",
    grep: "Grep",
    bash: "Bash",
    // A structural edit searches a set of paths; the extractor accepts file_paths.
    ast_edit: "Edit",
    ast_grep: "Grep",
  };
  const renamed = rename[toolName];
  if (renamed) {
    const paths = Array.isArray(toolInput.paths)
      ? toolInput.paths.filter((path): path is string => typeof path === "string" && path.trim() !== "")
      : [];
    return {
      tool_name: renamed,
      tool_input: paths.length > 0 ? { ...toolInput, file_paths: paths } : toolInput,
    };
  }

  if (toolName === "task") {
    // The extractor keys subagent dispatches on `description`.
    const label = safeString(toolInput.label) ?? safeString(toolInput.description);
    const prompt = safeString(toolInput.prompt);
    const description = label ?? (prompt ? prompt.split("\n")[0].slice(0, 200) : undefined);
    return {
      tool_name: "Agent",
      tool_input: description ? { ...toolInput, description } : toolInput,
    };
  }

  if (toolName === "ask") {
    // A user answer is a durable decision: the extractor reads one question and
    // the response text.
    const questions = Array.isArray(toolInput.questions) ? toolInput.questions : [];
    const first = questions.find(isRecord);
    const question = first ? [safeString(first.header), safeString(first.question)].filter(Boolean).join(": ") : "";
    return {
      tool_name: "AskUserQuestion",
      tool_input: question ? { ...toolInput, question } : toolInput,
      ...(toolContent !== undefined ? { tool_response: toolContent } : {}),
    };
  }

  if (toolName === "manage_skill") {
    const skill = safeString(toolInput.name) ?? safeString(toolInput.skill);
    return {
      tool_name: "Skill",
      tool_input: skill ? { ...toolInput, skill } : toolInput,
    };
  }

  return { tool_name: toolName, tool_input: toolInput };
}

function contextFromResponse(response: unknown): string | undefined {
  if (!isRecord(response) || typeof response.context !== "string" || !response.context.trim()) return undefined;
  return response.context;
}

/** Register OMP's hooks while making each host callback fail-open. */
export default function lcm(pi: HookApi): void {
  let restoreContext = "";
  let firstPrompt = true;

  const safe = (label: string, handler: HookHandler): HookHandler => async (event, ctx) => {
    try {
      return await handler(event, ctx);
    } catch (error) {
      logError(pi, label, error);
      return undefined;
    }
  };

  const register = (event: string, label: string, handler: HookHandler): void => {
    try {
      pi.on(event, safe(label, handler));
    } catch (error) {
      logError(pi, `${label} registration`, error);
    }
  };

  const fireIngest = (ctx: HookContext, timeoutMs = DEFAULT_TIMEOUT_MS, eventIdentity?: SessionIdentity): void => {
    const identity = eventIdentity ?? sessionIdentity(ctx);
    if (!identity) return;
    void post("/ingest", ingestBody(identity), {
      timeoutMs,
      fireAndForget: true,
    });
  };

  register("session_start", "session_start", async (_rawEvent, ctx) => {
    restoreContext = "";
    firstPrompt = true;
    const identity = sessionIdentity(ctx);
    if (!identity) return undefined;
    const base = identityBody(identity);
    // Capture before restore, and wait for it: restore reads the stored conversation,
    // and a session lcm has not ingested yet would answer from the project's latest
    // *other* conversation while this session's capture is still in flight.
    await post("/ingest", ingestBody(identity));
    const restored = await post("/restore", { ...base, source: "startup" });
    const context = contextFromResponse(restored);
    if (context) restoreContext = context;
    void post("/session-start-compact", base, { fireAndForget: true });
    return undefined;
  });

  register("before_agent_start", "before_agent_start", async (rawEvent, ctx) => {
    const event = rawEvent as Partial<BeforeAgentStartEvent>;
    const restored = firstPrompt ? restoreContext : "";
    if (firstPrompt) {
      restoreContext = "";
      firstPrompt = false;
    }

    let searched: string | undefined;
    const identity = sessionIdentity(ctx);
    if (identity && typeof event.prompt === "string") {
      const result = await post("/prompt-search", {
        ...identityBody(identity),
        query: event.prompt,
        nativeHistory: true,
        learningInstructionBytes: 0,
        format: "context",
      });
      searched = contextFromResponse(result);
    }

    const content = [restored, searched].filter((text): text is string => Boolean(text?.trim())).join("\n\n");
    if (!content) return undefined;
    // OMP keeps only the FIRST returned message, so restore and prompt hints must be combined here.
    return memoryMessage(content);
  });

  register("agent_end", "agent_end", async (rawEvent, ctx) => {
    const event = rawEvent as AgentEndEvent;
    if (event.willContinue !== true) fireIngest(ctx);
    return undefined;
  });

  register("session_stop", "session_stop", async (rawEvent, ctx) => {
    const event = rawEvent as SessionStopEvent;
    fireIngest(ctx, DEFAULT_TIMEOUT_MS, sessionStopIdentity(ctx, event));
    return undefined;
  });

  register("tool_result", "tool_result", async (rawEvent, ctx) => {
    const event = rawEvent as Partial<ToolResultEvent>;
    const identity = sessionIdentity(ctx);
    const toolName = safeString(event.toolName);
    if (!identity || !toolName) return undefined;
    const input = isRecord(event.input) ? event.input : {};
    const toolContent = boundedToolContent(event.content);
    const isError = event.isError === true;
    const normalized = normalizeOmpTool(toolName, input, toolContent);
    const body: Record<string, unknown> = {
      ...identityBody(identity),
      tool_name: normalized.tool_name,
      tool_input: normalized.tool_input,
      ...(safeString(event.toolCallId) ? { tool_use_id: event.toolCallId } : {}),
      ...(normalized.tool_response !== undefined
        ? { tool_response: normalized.tool_response }
        : toolContent !== undefined ? { tool_response: toolContent } : {}),
      ...(isError ? { tool_output: { isError: true }, error: toolContent } : {}),
      ...(modelName(ctx) ? { model: modelName(ctx) } : {}),
      hook_event_name: isError ? "PostToolUseFailure" : "PostToolUse",
    };
    void post("/tool-event", body, { fireAndForget: true });
    return undefined;
  });

  register("session_before_compact", "session_before_compact", async (_rawEvent, ctx) => {
    const identity = sessionIdentity(ctx);
    if (!identity) return undefined;
    const body = identityBody(identity);
    void post("/ingest", ingestBody(identity), { fireAndForget: true });
    void post("/compact", { ...body, skip_ingest: true }, { fireAndForget: true });
    return undefined;
  });

  register("session_shutdown", "session_shutdown", async (_rawEvent, ctx) => {
    fireIngest(ctx, SHUTDOWN_TIMEOUT_MS);
    return undefined;
  });
}
