// Generated by lcm. Local edits are overwritten by `lcm connectors install omp`.
// lcm's Oh My Pi hook adapter.
//
// The local interfaces mirror OMP v18.2.6's `extensibility/hooks` types. The
// adapter is loaded directly by Bun, so it deliberately depends only on Node
// builtins and keeps the daemon protocol here instead of importing this package.
import { readFileSync } from "node:fs";
import { request as httpRequest } from "node:http";
import { Buffer } from "node:buffer";
import { join } from "node:path";

const DEFAULT_PORT = 3737;
const DEFAULT_TIMEOUT_MS = 1_500;
const SHUTDOWN_TIMEOUT_MS = 250;
const TOOL_CONTENT_CAP = 2_000;

export interface HookLogger {
  error?: (message: string) => void;
  warn?: (message: string) => void;
  info?: (message: string) => void;
}

export interface HookContext {
  cwd?: string;
  hasUI?: boolean;
  model?: unknown;
  sessionManager?: {
    getSessionId?: () => string | undefined;
    getSessionFile?: () => string | undefined;
    getCwd?: () => string | undefined;
    /** OMP's own signal that the session file exists; persistence is lazy. */
    isSessionOnDisk?: () => boolean;
  };
}

export type HookHandler = (event: unknown, ctx: HookContext) => Promise<unknown> | unknown;

/** The small part of OMP's hook API this module needs. */
export interface HookApi {
  on: (event: string, handler: HookHandler) => void;
  sendMessage?: (message: unknown, options?: unknown) => unknown;
  logger?: HookLogger | ((message: string) => void);
}

export interface ResolvedDaemon {
  home: string;
  port: number;
  token?: string;
}

export interface SessionIdentity {
  sessionId: string;
  cwd: string;
  transcriptPath?: string;
}

export interface PostOptions {
  timeoutMs?: number;
  /** Capture calls use this so the hook never waits for the daemon response. */
  fireAndForget?: boolean;
}

export interface TransportRequest {
  path: string;
  body: Record<string, unknown>;
  port: number;
  token?: string;
  timeoutMs: number;
  fireAndForget: boolean;
}

export type Transport = (request: TransportRequest) => Promise<unknown | undefined> | unknown;

export interface SessionStartEvent {
  type?: string;
}

export interface BeforeAgentStartEvent {
  type?: string;
  prompt: string;
  images?: unknown;
  systemPrompt?: string;
}

export interface AgentEndEvent {
  type?: string;
  messages?: unknown;
  willContinue?: boolean;
}

export interface SessionStopEvent {
  type?: string;
  session_id?: string;
  session_file?: string;
  messages?: unknown;
  turn_id?: string;
  last_assistant_message?: string;
  stop_hook_active?: boolean;
  signal?: string;
}

export interface ToolResultEvent {
  toolName: string;
  toolCallId?: string;
  input?: unknown;
  content?: unknown;
  details?: unknown;
  isError?: boolean;
}

export interface SessionBeforeCompactEvent {
  type?: string;
  preparation?: unknown;
  branchEntries?: unknown;
  customInstructions?: string;
  signal?: string;
}

export interface SessionShutdownEvent {
  type?: string;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function safeString(value: unknown): string | undefined {
  return typeof value === "string" && value.trim() ? value : undefined;
}

/** Resolve the daemon address without letting malformed local state break the host. */
export function resolveDaemon(): ResolvedDaemon {
  const configuredHome = typeof process.env.LCM_HOME === "string" ? process.env.LCM_HOME.trim() : "";
  const homeRoot = configuredHome || (typeof process.env.HOME === "string" ? process.env.HOME.trim() : "");
  const home = homeRoot ? (configuredHome || join(homeRoot, ".lossless-claude")) : ".lossless-claude";

  let port = DEFAULT_PORT;
  try {
    const config = JSON.parse(readFileSync(join(home, "config.json"), "utf8")) as unknown;
    const configuredPort = isRecord(config) && isRecord(config.daemon) ? config.daemon.port : undefined;
    if (typeof configuredPort === "number" && Number.isFinite(configuredPort)) port = configuredPort;
  } catch {
    // A missing or partially-written config is equivalent to the default config.
  }

  let token: string | undefined;
  try {
    const value = readFileSync(join(home, "daemon.token"), "utf8").trim();
    if (value) token = value;
  } catch {
    // Authentication is optional for older or development daemons.
  }
  return token ? { home, port, token } : { home, port };
}

function clearTimer(timer: ReturnType<typeof setTimeout>): void {
  clearTimeout(timer);
}

/** Node transport used in production; sockets and timers are unreferenced for capture calls. */
const nodeTransport: Transport = (request) => new Promise<unknown | undefined>((resolve) => {
  let json: string;
  try {
    json = JSON.stringify(request.body);
  } catch {
    resolve(undefined);
    return;
  }

  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), request.timeoutMs);
  timeout.unref?.();
  let settled = false;
  const finish = (value: unknown | undefined): void => {
    if (settled) return;
    settled = true;
    clearTimer(timeout);
    resolve(value);
  };

  let req: ReturnType<typeof httpRequest>;
  try {
    req = httpRequest({
      hostname: "127.0.0.1",
      port: request.port,
      path: request.path,
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Content-Length": Buffer.byteLength(json),
        ...(request.token ? { Authorization: `Bearer ${request.token}` } : {}),
      },
    }, (res) => {
      if (request.fireAndForget) {
        res.resume();
        return;
      }
      const chunks: Buffer[] = [];
      res.on("data", (chunk: Buffer | string) => chunks.push(Buffer.from(chunk)));
      res.on("end", () => {
        if ((res.statusCode ?? 0) < 200 || (res.statusCode ?? 0) >= 300) {
          finish(undefined);
          return;
        }
        const text = Buffer.concat(chunks).toString("utf8").trim();
        if (!text) {
          finish(undefined);
          return;
        }
        try {
          finish(JSON.parse(text) as unknown);
        } catch {
          finish(undefined);
        }
      });
    });
  } catch {
    finish(undefined);
    return;
  }

  const onAbort = (): void => {
    req.destroy(new Error("daemon request timed out"));
  };
  controller.signal.addEventListener("abort", onAbort, { once: true });
  req.on("error", () => finish(undefined));
  req.setTimeout(request.timeoutMs, () => controller.abort());
  if (request.fireAndForget) {
    req.on("socket", (socket) => {
      req.on("finish", () => socket.unref());
    });
  }
  try {
    req.write(json);
    req.end();
  } catch {
    finish(undefined);
    return;
  }

  // The caller must not wait for capture requests. The socket is unreferenced
  // after the body flushes, while errors remain intentionally best-effort.
  if (request.fireAndForget) {
    settled = true;
    clearTimer(timeout);
    resolve(undefined);
  }
});

let activeTransport: Transport = nodeTransport;

/** Replace the wire transport in focused tests; passing undefined restores Node HTTP. */
export function __setTransportForTests(transport?: Transport): void {
  activeTransport = transport ?? nodeTransport;
}

/** POST JSON to the local daemon, failing closed when it is unavailable. */
export async function post(
  path: string,
  body: Record<string, unknown>,
  options: PostOptions = {},
): Promise<unknown | undefined> {
  const daemon = resolveDaemon();
  const request: TransportRequest = {
    path: path.startsWith("/") ? path : `/${path}`,
    body,
    port: daemon.port,
    token: daemon.token,
    timeoutMs: options.timeoutMs ?? DEFAULT_TIMEOUT_MS,
    fireAndForget: options.fireAndForget === true,
  };

  if (request.fireAndForget) {
    try {
      Promise.resolve(activeTransport(request)).catch(() => undefined);
    } catch {
      // Capture is deliberately best-effort.
    }
    return undefined;
  }
  try {
    return await activeTransport(request);
  } catch {
    return undefined;
  }
}

/** Read the identity that is valid for every daemon call. */
export function sessionIdentity(ctx: HookContext | undefined): SessionIdentity | undefined {
  try {
    const sessionId = ctx?.sessionManager?.getSessionId?.();
    const cwd = ctx?.cwd;
    if (typeof sessionId !== "string" || !sessionId.trim() || typeof cwd !== "string" || !cwd.trim()) return undefined;
    const transcriptPath = safeString(ctx?.sessionManager?.getSessionFile?.());
    return transcriptPath ? { sessionId, cwd, transcriptPath } : { sessionId, cwd };
  } catch {
    return undefined;
  }
}

/**
 * Whether OMP has written this session's file yet.
 *
 * OMP keeps a new session in memory until it holds an assistant message, so
 * `getSessionFile()` can name a path that leads nowhere. The daemon refuses a
 * supplied transcript path it cannot read, which would answer every first
 * capture of a fresh session with a 400; skipping the capture until the harness
 * says the file exists is the same signal OMP's own resume hint gates on. An
 * older OMP without the method is treated as on-disk, which is the old behavior.
 */
function sessionOnDisk(ctx: HookContext | undefined): boolean {
  try {
    const isOnDisk = ctx?.sessionManager?.isSessionOnDisk;
    return typeof isOnDisk !== "function" || isOnDisk.call(ctx?.sessionManager) !== false;
  } catch {
    return true;
  }
}

function sessionStopIdentity(ctx: HookContext | undefined, event: SessionStopEvent): SessionIdentity | undefined {
  const current = sessionIdentity(ctx);
  const sessionId = current?.sessionId ?? safeString(event.session_id);
  const cwd = current?.cwd;
  if (!sessionId || !cwd) return undefined;
  const transcriptPath = current?.transcriptPath ?? safeString(event.session_file);
  return transcriptPath ? { sessionId, cwd, transcriptPath } : { sessionId, cwd };
}

function identityBody(identity: SessionIdentity): Record<string, unknown> {
  return {
    session_id: identity.sessionId,
    cwd: identity.cwd,
    client: "omp",
  };
}

function ingestBody(identity: SessionIdentity): Record<string, unknown> {
  return {
    ...identityBody(identity),
    ...(identity.transcriptPath ? { transcript_path: identity.transcriptPath } : {}),
    source: "live",
  };
}

function logError(pi: HookApi, label: string, error: unknown): void {
  try {
    const message = `[lcm] ${label}: ${error instanceof Error ? error.message : String(error)}`;
    if (typeof pi.logger === "function") pi.logger(message);
    else if (pi.logger?.error) pi.logger.error(message);
    else if (pi.logger?.warn) pi.logger.warn(message);
    else pi.logger?.info?.(message);
  } catch {
    // Logging must not become a hook failure.
  }
}

function modelName(ctx: HookContext): string | undefined {
  const model = ctx.model;
  if (typeof model === "string" && model.trim()) return model;
  if (!isRecord(model)) return undefined;
  return safeString(model.id) ?? safeString(model.name);
}

function boundedToolContent(value: unknown): string | undefined {
  if (value === undefined) return undefined;
  let text: string;
  if (typeof value === "string") text = value;
  else {
    const texts = (Array.isArray(value) ? value : [])
      .filter(isRecord)
      .map((block) => block.text)
      .filter((part): part is string => typeof part === "string");
    if (texts.length > 0) {
      // OMP tool results are content blocks; a decision's answer must read as
      // text, not as its JSON envelope.
      text = texts.join("\n");
    } else {
      try {
        text = JSON.stringify(value) ?? String(value);
      } catch {
        text = String(value);
      }
    }
  }
  return text.length > TOOL_CONTENT_CAP ? `${text.slice(0, TOOL_CONTENT_CAP)}...` : text;
}

function memoryMessage(content: string): { message: Record<string, unknown> } {
  return {
    message: {
      customType: "lcm-memory",
      content,
      display: true,
      attribution: "agent",
    },
  };
}

/** One tool call as OMP reported it. */
export interface OmpToolCall {
  readonly toolName: string;
  readonly input: Record<string, unknown>;
}

type OmpToolMapping =
  | { readonly canonical: string; readonly input?: (call: OmpToolCall) => Record<string, unknown> | undefined }
  | { readonly silent: string };

/** `todo` operations as the status word the stored memory reads better with. */
const TODO_STATUS: Record<string, string> = {
  init: "created",
  append: "created",
  start: "in_progress",
  // OMP's own unblock returns the item to pending and clears its blocker.
  unblock: "pending",
  done: "completed",
  rm: "abandoned",
  drop: "abandoned",
  block: "blocked",
};

/** GitHub operations that change something; the reads and searches record nothing. */
const GITHUB_WRITE_OPS = ["pr_create", "pr_push", "pr_checkout", "run_watch"];

/** Actions that start a scan; polling or validating one is not an act of its own. */
const SCAN_START_ACTIONS = ["start", "cloud_start"];

function withPathSet(call: OmpToolCall): Record<string, unknown> {
  const paths = Array.isArray(call.input.paths)
    ? call.input.paths.filter((path): path is string => typeof path === "string" && path.trim() !== "")
    : [];
  // A structural edit or search names a set of paths; the extractor accepts file_paths.
  return paths.length === 0 ? { ...call.input } : { ...call.input, file_paths: paths };
}

function firstTodoItem(list: unknown): string | undefined {
  if (!Array.isArray(list)) return undefined;
  for (const phase of list) {
    if (!isRecord(phase) || !Array.isArray(phase.items)) continue;
    const item = phase.items.find((entry): entry is string => typeof entry === "string" && entry.trim() !== "");
    if (item !== undefined) return item;
  }
  return undefined;
}

function contextChange(call: OmpToolCall, kind: string, detail: string | undefined): Record<string, unknown> {
  return detail === undefined ? { ...call.input, kind } : { ...call.input, kind, detail };
}

/**
 * OMP's tool ids, onto the daemon extractor's vocabulary.
 *
 * Inlined rather than imported: OMP loads this module in-process with no package
 * resolution, so it cannot reach lcm's own seam (src/hooks/tool-vocabulary.ts).
 * `test/omp-hook.test.ts` holds the two together instead, by putting every translated
 * call through the real extractor, where a mapping that stops producing events fails.
 *
 * A mapper may decline a payload too thin for its shape; the call then travels under its
 * own name, so the extractor's generic arms still see it. A `silent` entry records the
 * same thing with the reason written down, so coverage can be audited rather than guessed.
 */
const OMP_TOOL_VOCABULARY: Record<string, OmpToolMapping> = {
  read: { canonical: "Read" },
  write: { canonical: "Write" },
  edit: { canonical: "Edit" },
  glob: { canonical: "Glob" },
  grep: { canonical: "Grep" },
  bash: { canonical: "Bash" },
  ast_edit: { canonical: "Edit", input: withPathSet },
  ast_grep: { canonical: "Grep", input: withPathSet },
  task: {
    canonical: "Agent",
    // The extractor keys subagent dispatches on `description`.
    input: (call) => {
      const label = safeString(call.input.label) ?? safeString(call.input.description);
      const prompt = safeString(call.input.prompt);
      const description = label ?? (prompt === undefined ? undefined : prompt.split("\n")[0]);
      return description === undefined ? undefined : { ...call.input, description };
    },
  },
  ask: {
    canonical: "AskUserQuestion",
    // A user answer is a durable decision: the extractor reads one question, and the
    // response travels as the tool's response text.
    input: (call) => {
      const questions = Array.isArray(call.input.questions) ? call.input.questions : [];
      const first = questions.find(isRecord);
      const question = first === undefined
        ? undefined
        : [safeString(first.header), safeString(first.question)].filter(Boolean).join(": ");
      return question ? { ...call.input, question } : undefined;
    },
  },
  manage_skill: {
    canonical: "Skill",
    input: (call) => {
      const skill = safeString(call.input.name) ?? safeString(call.input.skill);
      return skill === undefined ? undefined : { ...call.input, skill };
    },
  },
  todo: {
    canonical: "TaskUpdate",
    // Real shape: { op, list?: [{phase, items}], task?, phase?, items?, reason? }, with
    // ops init | start | done | rm | drop | block | unblock | append | view.
    input: (call) => {
      const op = safeString(call.input.op);
      const status = op === undefined ? undefined : TODO_STATUS[op];
      const subject = safeString(call.input.task) ?? firstTodoItem(call.input.list) ?? safeString(call.input.phase);
      // `view` reads the list, and a call that names no task says nothing.
      if (status === undefined || subject === undefined) return undefined;
      return { ...call.input, subject, status };
    },
  },
  github: {
    canonical: "GitHub",
    input: (call) => {
      const op = safeString(call.input.op);
      if (op === undefined || !GITHUB_WRITE_OPS.includes(op)) return undefined;
      const detail = safeString(call.input.title) ?? safeString(call.input.pr) ?? safeString(call.input.repo);
      return detail === undefined ? { ...call.input, op } : { ...call.input, op, detail };
    },
  },
  security_scan: {
    canonical: "SecurityScan",
    input: (call) => {
      const action = safeString(call.input.action);
      if (action === undefined || !SCAN_START_ACTIONS.includes(action)) return undefined;
      const target = safeString(call.input.target_kind);
      return target === undefined ? { ...call.input, action } : { ...call.input, action, target_kind: target };
    },
  },
  context_notes: {
    canonical: "ContextNote",
    // Writing a note replaces the notebook; reading it (no text) is not an act.
    input: (call) => {
      const text = safeString(call.input.text);
      return text === undefined ? undefined : { ...call.input, text };
    },
  },
  checkpoint: {
    canonical: "ContextChange",
    input: (call) => contextChange(call, "checkpoint", safeString(call.input.goal)),
  },
  rewind: {
    canonical: "ContextChange",
    input: (call) => {
      const report = safeString(call.input.report);
      return contextChange(call, "rewind", report === undefined ? undefined : report.split("\n")[0]);
    },
  },
  new_context: { canonical: "ContextChange", input: (call) => contextChange(call, "reset", undefined) },

  // OMP's own long-term memory. Recording it would duplicate lcm's memory and risk the
  // feedback loop the extractor already guards against for lcm_store.
  retain: { silent: "the harness's own long-term memory" },
  recall: { silent: "a read of the harness's own memory" },
  reflect: { silent: "a read of the harness's own memory" },
  learn: { silent: "the harness's own long-term memory" },
  memory_edit: { silent: "the harness's own memory files" },
  // Queries and out-of-band plumbing: no durable fact.
  lsp: { silent: "language-server query" },
  eval: { silent: "in-process evaluation" },
  debug: { silent: "debugger control" },
  hub: { silent: "out-of-band messaging" },
  web_search: { silent: "a search leaves no durable fact" },
  goal: { silent: "loop control" },
  yield: { silent: "loop control" },
  think: { silent: "reasoning, not an act" },
};

/**
 * Translate one OMP tool call for the daemon's extractor.
 *
 * Never discards a call: an unmapped id, a silent id, and a payload a mapper declines all
 * travel under OMP's own name, where the extractor's generic arms can still act on them.
 */
export function translateOmpTool(call: OmpToolCall): { tool_name: string; tool_input: Record<string, unknown> } {
  const passthrough = { tool_name: call.toolName, tool_input: { ...call.input } };
  const mapping = OMP_TOOL_VOCABULARY[call.toolName];
  if (mapping === undefined || "silent" in mapping) return passthrough;

  const input = mapping.input === undefined ? call.input : mapping.input(call);
  return input === undefined ? passthrough : { tool_name: mapping.canonical, tool_input: input };
}

function contextFromResponse(response: unknown): string | undefined {
  if (!isRecord(response) || typeof response.context !== "string" || !response.context.trim()) return undefined;
  return response.context;
}

/** Register OMP's hooks while making each host callback fail-open. */
export default function lcm(pi: HookApi): void {
  let restoreContext = "";
  let firstPrompt = true;

  const safe = (label: string, handler: HookHandler): HookHandler => async (event, ctx) => {
    try {
      return await handler(event, ctx);
    } catch (error) {
      logError(pi, label, error);
      return undefined;
    }
  };

  const register = (event: string, label: string, handler: HookHandler): void => {
    try {
      pi.on(event, safe(label, handler));
    } catch (error) {
      logError(pi, `${label} registration`, error);
    }
  };

  const fireIngest = (ctx: HookContext, timeoutMs = DEFAULT_TIMEOUT_MS, eventIdentity?: SessionIdentity): void => {
    const identity = eventIdentity ?? sessionIdentity(ctx);
    if (!identity || !sessionOnDisk(ctx)) return;
    void post("/ingest", ingestBody(identity), {
      timeoutMs,
      fireAndForget: true,
    });
  };

  register("session_start", "session_start", async (_rawEvent, ctx) => {
    restoreContext = "";
    firstPrompt = true;
    const identity = sessionIdentity(ctx);
    if (!identity) return undefined;
    const base = identityBody(identity);
    // Capture before restore, and wait for it: restore reads the stored conversation,
    // and a session lcm has not ingested yet would answer from the project's latest
    // *other* conversation while this session's capture is still in flight.
    if (sessionOnDisk(ctx)) await post("/ingest", ingestBody(identity));
    const restored = await post("/restore", { ...base, source: "startup" });
    const context = contextFromResponse(restored);
    if (context) restoreContext = context;
    void post("/session-start-compact", base, { fireAndForget: true });
    return undefined;
  });

  register("before_agent_start", "before_agent_start", async (rawEvent, ctx) => {
    const event = rawEvent as Partial<BeforeAgentStartEvent>;
    const restored = firstPrompt ? restoreContext : "";
    if (firstPrompt) {
      restoreContext = "";
      firstPrompt = false;
    }

    let searched: string | undefined;
    const identity = sessionIdentity(ctx);
    if (identity && typeof event.prompt === "string") {
      const result = await post("/prompt-search", {
        ...identityBody(identity),
        query: event.prompt,
        nativeHistory: true,
        learningInstructionBytes: 0,
        format: "context",
      });
      searched = contextFromResponse(result);
    }

    const content = [restored, searched].filter((text): text is string => Boolean(text?.trim())).join("\n\n");
    if (!content) return undefined;
    // OMP keeps only the FIRST returned message, so restore and prompt hints must be combined here.
    return memoryMessage(content);
  });

  register("agent_end", "agent_end", async (rawEvent, ctx) => {
    const event = rawEvent as AgentEndEvent;
    if (event.willContinue !== true) fireIngest(ctx);
    return undefined;
  });

  register("session_stop", "session_stop", async (rawEvent, ctx) => {
    const event = rawEvent as SessionStopEvent;
    fireIngest(ctx, DEFAULT_TIMEOUT_MS, sessionStopIdentity(ctx, event));
    return undefined;
  });

  register("tool_result", "tool_result", async (rawEvent, ctx) => {
    const event = rawEvent as Partial<ToolResultEvent>;
    const identity = sessionIdentity(ctx);
    const toolName = safeString(event.toolName);
    if (!identity || !toolName) return undefined;
    const input = isRecord(event.input) ? event.input : {};
    const toolContent = boundedToolContent(event.content);
    const isError = event.isError === true;
    const translated = translateOmpTool({ toolName, input });
    const body: Record<string, unknown> = {
      ...identityBody(identity),
      tool_name: translated.tool_name,
      tool_input: translated.tool_input,
      ...(safeString(event.toolCallId) ? { tool_use_id: event.toolCallId } : {}),
      ...(toolContent !== undefined ? { tool_response: toolContent } : {}),
      ...(isError ? { tool_output: { isError: true }, error: toolContent } : {}),
      ...(modelName(ctx) ? { model: modelName(ctx) } : {}),
      hook_event_name: isError ? "PostToolUseFailure" : "PostToolUse",
    };
    void post("/tool-event", body, { fireAndForget: true });
    return undefined;
  });

  register("session_before_compact", "session_before_compact", async (_rawEvent, ctx) => {
    const identity = sessionIdentity(ctx);
    if (!identity) return undefined;
    const body = identityBody(identity);
    if (sessionOnDisk(ctx)) void post("/ingest", ingestBody(identity), { fireAndForget: true });
    void post("/compact", { ...body, skip_ingest: true }, { fireAndForget: true });
    return undefined;
  });

  register("session_shutdown", "session_shutdown", async (_rawEvent, ctx) => {
    fireIngest(ctx, SHUTDOWN_TIMEOUT_MS);
    return undefined;
  });
}
