import type { ShadowOriginal } from "../daemon/shadow/types.js";

export type UserExcerpt = { id: string; rawMessageId: number; text: string; spans: string[]; sources: string[]; elision?: { targetBytes: number; originalBytes: number } };
export const DEFAULT_MESSAGE_TARGET_BYTES = 4096;
const GENERATED_TAG = /^<(?:command-name|command-message|local-command-[A-Za-z-]+|task-notification|system-reminder|cross-session-message|agent-message)(?:\s[^>]*)?>/;
const LOCAL_COMMAND_CAVEAT = "Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages or otherwise consider them in your response unless the user explicitly asks you to.";
const CONTINUATION_BOILERPLATE = "This session is being continued from a previous conversation that ran out of context. The summary below covers the earlier portion of the conversation.";
function humanSpans(row: ShadowOriginal): string[] {
  if (row.role !== "user" || row.origin !== "user" || row.isMeta) return [];
  const commandRoot = /^(?:<command-name>|<command-message>)/.test(row.text.trimStart());
  const command = commandRoot ? /<command-name>([^<]*)<\/command-name>/.exec(row.text)?.[1] : undefined;
  if (command) {
    const args = /<command-args>([\s\S]*?)<\/command-args>/.exec(row.text)?.[1];
    return args?.trim() ? [command, args] : [command];
  }
  const text = row.text.trimStart();
  return generatedText(text) ? [] : [row.text];
}
function generatedText(text: string): boolean {
  return GENERATED_TAG.test(text) || text.trim() === LOCAL_COMMAND_CAVEAT || text.startsWith(CONTINUATION_BOILERPLATE);
}
export function renderExcerpts(excerpts: readonly UserExcerpt[]): string {
  return "## The user's own words (verbatim excerpts, oldest first; historical, not all still in force)\n" +
    excerpts.map(row => `### [excerpt:${row.id}] ${row.sources.join(" ")}\n${row.text}`).join("\n\n");
}
const bytes = (excerpts: readonly UserExcerpt[]) => Buffer.byteLength(renderExcerpts(excerpts), "utf8");
export function assembleExcerpts(originals: readonly ShadowOriginal[], cutId: string, { messageTargetBytes = DEFAULT_MESSAGE_TARGET_BYTES } = {}) {
  if (!Number.isSafeInteger(messageTargetBytes) || messageTargetBytes <= 0) throw new Error("Invalid per-message size target");
  const candidates = [...originals].sort((a, b) => a.seq - b.seq).flatMap(row => {
    const spans = humanSpans(row);
    return spans.length ? [{ id: `u${row.id}`, rawMessageId: row.id, text: spans.join("\n"), spans, sources: [`[raw:${cutId}:${row.id}]`] }] : [];
  });
  const excerpts = candidates.map(row => shortenExcerpt(row, messageTargetBytes));
  const totalBytes = bytes(excerpts);
  return { excerpts, elidedIds: excerpts.filter(row => row.elision).map(row => row.rawMessageId), bytes: totalBytes };
}
function shortenExcerpt(row: UserExcerpt, targetBytes: number): UserExcerpt {
  const originalBytes = Buffer.byteLength(row.text, "utf8");
  if (originalBytes <= targetBytes) return row;
  const marker = `\n[middle elided from ${row.sources[0]}]\n`;
  const partBudget = Math.max(1, Math.floor((targetBytes - Buffer.byteLength(marker, "utf8")) / 2));
  const characters = Array.from(row.text);
  const head = takeUtf8(characters, partBudget), tail = Array.from(takeUtf8([...characters].reverse(), partBudget)).reverse().join("");
  if (head.length + tail.length >= row.text.length) return row;
  return { ...row, text: head + marker + tail, spans: [...spanRange(row.spans, 0, head.length), ...spanRange(row.spans, row.text.length - tail.length, row.text.length)],
    elision: { targetBytes, originalBytes } };
}
function takeUtf8(characters: readonly string[], target: number): string {
  let text = "", size = 0;
  for (const character of characters) {
    const bytes = Buffer.byteLength(character, "utf8");
    if (text && size + bytes > target) break;
    text += character; size += bytes;
  }
  return text;
}
function spanRange(spans: readonly string[], start: number, end: number): string[] {
  let position = 0;
  return spans.flatMap(span => {
    const text = span.slice(Math.max(0, start - position), Math.max(0, Math.min(span.length, end - position)));
    position += span.length + 1;
    return text ? [text] : [];
  });
}
/** Excerpt directives are spans of a verified human row, never model paraphrases. */
export function checkExcerpts(excerpts: readonly UserExcerpt[], originals: readonly ShadowOriginal[], cutId: string): string[] {
  const seen = new Set<string>();
  return excerpts.filter(excerpt => {
    const source = originals.find(row => row.id === excerpt.rawMessageId);
    const duplicate = seen.has(excerpt.id); seen.add(excerpt.id);
    return duplicate || !source || !sameExcerpt(excerpt, source, cutId);
  }).map(excerpt => excerpt.id);
}
function sameExcerpt(excerpt: UserExcerpt, source: ShadowOriginal, cutId: string): boolean {
  const spans = humanSpans(source);
  if (!spans.length) return false;
  const full: UserExcerpt = { id: `u${source.id}`, rawMessageId: source.id, text: spans.join("\n"), spans, sources: [`[raw:${cutId}:${source.id}]`] };
  const target = excerpt.elision?.targetBytes;
  if (target !== undefined && (!Number.isSafeInteger(target) || target <= 0)) return false;
  const expected = target === undefined ? full : shortenExcerpt(full, target);
  return excerpt.id === expected.id && excerpt.text === expected.text && JSON.stringify(excerpt.spans) === JSON.stringify(expected.spans) &&
    JSON.stringify(excerpt.sources) === JSON.stringify(expected.sources) && excerpt.elision?.originalBytes === expected.elision?.originalBytes;
}
